### ISSUE TITLE
can't upload image

### ISSUE THREAD

**Issue by pdkhanh3011** [Prajwal100/Complete-Ecommerce-in-laravel-10#92]
i have this issue when i try upload img, pls help me

![image](https://github.com/Prajwal100/Advance-Ecommerce-in-laravel-7/assets/82632380/80c143ad-371a-41bb-b98e-f3a39ab0eb6f)

**Comment by pdkhanh3011** [comment]
yes

**Comment by Prajwal100** [comment]
@pdkhanh3011 can you please try to set your domain name in APP_URL (.env file)

![image](https://github.com/Prajwal100/Advance-Ecommerce-in-laravel-7/assets/29488275/51a68588-9d01-4316-9cd3-0d273a677647)

**Comment by pdkhanh3011** [comment]
tks u, i fixed it by assigning permission 777 to the storage folder
